//////////////////////////////////////////////////////////////////////////////
// File: commTester.nc
//
//
// Generated by NodeBuilder Code Wizard Version 4.40.15
// Copyright (c) 2001-2026 EnOcean Corporation.  All rights reserved.
//
// ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
// ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
// ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
// ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
// QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE,
// NONINFRINGEMENT, AND THEIR EQUIVALENTS.
//
//
// Written By: RTG  
//
// Description:  Business logic for the comm performance testing of FT communication
//
// commTester.nc contains when-tasks, handler functions, director functions and
// any other code that is used with the commTester component.
//
//////////////////////////////////////////////////////////////////////////////

#ifndef _commTester_NC_
#define _commTester_NC_

#include <status.h>
#include <msg_addr.h>
#include <addrdefs.h>
#include <s32.h>
#include "commTester.h"

mtimer startDelayTmr;
mtimer paceDelayTmr;
mtimer repeating failFlashTmr;

boolean boundNvs[NVO_COUNT];
boolean progressSt = LED_OFF;
unsigned activeNv = 0;
unsigned nvsInPlay = 0;
s32_type testCount;
s32_type failTotal;
s32_type txCount;
s32_type lastCountValue;
msg_tag bind_info(nonbind) bcast_tag;
unsigned long paceLoadValue;
#define DATA_REQUEST 1
#define MSG_RESP_OK 2

//
// Function to broadcast a clear status message to all nodes on the network
//
void broadcastClearStatus() {
    msg_out.tag = bcast_tag;
    msg_out.code = 0x53;  // ND_CLEAR_STATUS
    msg_out.service = UNACKD_RPT;
    msg_out.dest_addr.bcast.type = BROADCAST;
    msg_out.dest_addr.bcast.domain = 0;
    msg_out.dest_addr.bcast.subnet = 0; 
    msg_out.dest_addr.bcast.backlog = 0;
    msg_out.dest_addr.bcast.rpt_timer = 2; // 32ms
    msg_out.dest_addr.bcast.retry = 8; 
    msg_out.dest_addr.bcast.tx_timer = 0;
    msg_send();
}

void bumpActive() {
    // Global variable activeNv manages round robin updates of
    // connected nvoTarget_[n] points.  
    s32_inc(&txCount);

    switch (activeNv)
    {
    case 0:
        nvoTarget_1 = testCount;
        break;
    case 1:
        nvoTarget_2 = testCount;
        break;
    case 2:
        nvoTarget_3 = testCount;
        break;
    case 3:
        nvoTarget_4 = testCount;
        break;
    case 4:
        nvoTarget_5 = testCount;
        break;
    case 5:
        nvoTarget_6 = testCount;
        break; 
    case 6:
        nvoTarget_7 = testCount;
        break;  
    case 7:
        nvoTarget_8 = testCount;
        break;
    case 8:
        nvoTarget_9 = testCount;
        break;
    case 9:
        nvoTarget_10 = testCount;
        break;
    case 10:
        nvoTarget_11 = testCount;
        break;
    case 11:
        nvoTarget_12 = testCount;
        break;
    case 12:
        nvoTarget_13 =  testCount;
        break;  
    case 13:
        nvoTarget_14 = testCount;
        break;
    case 14:
        nvoTarget_15 = testCount;
        break;    
    case 16:
        // Test run termination 
        //io_out(LED2, LED_ON);
        if (s32_gt(&failTotal, &s32_zero))
            failFlashTmr = 200;
        break;
    default:
        break;
    }
}

when (timer_expires(paceDelayTmr)) {
    // Stop if the limit is reached
    if (s32_ge(&txCount, &commTester::cpTestLimit)) 
        return;
    progressSt = !progressSt;
    io_out(LED2, progressSt);    
    if (commTester::cpUpdateRate) {
        if (activeNv == 0)
            s32_inc(&testCount);
        bumpActive();
        activeNv = activeNv < (nvsInPlay - 1 )? activeNv + 1 : 0;
    } 
}

when (timer_expires(failFlashTmr)) {
    progressSt = !progressSt;
    io_out(LED2, progressSt);
}

when (timer_expires(startDelayTmr)) {

    // Determine which NVs are in play if this device is one of the sender nodes
    if (commTester::cpUpdateRate) {
        broadcastClearStatus();
        io_out(LED1, LED_ON);
        boundNvs[0] = is_bound(nvoTarget_1);
        boundNvs[1] = is_bound(nvoTarget_2);
        boundNvs[2] = is_bound(nvoTarget_3);
        boundNvs[3] = is_bound(nvoTarget_4);
        boundNvs[4] = is_bound(nvoTarget_5);
        boundNvs[5] = is_bound(nvoTarget_6);
        boundNvs[6] = is_bound(nvoTarget_7);
        boundNvs[7] = is_bound(nvoTarget_8);
        boundNvs[8] = is_bound(nvoTarget_9);
        boundNvs[9] = is_bound(nvoTarget_10);
        boundNvs[10] = is_bound(nvoTarget_11);
        boundNvs[11] = is_bound(nvoTarget_12);
        boundNvs[12] = is_bound(nvoTarget_13);
        boundNvs[13] = is_bound(nvoTarget_14);
        boundNvs[14] = is_bound(nvoTarget_15);
        activeNv = 0;
        while (activeNv < NVO_COUNT) {
            nvsInPlay += boundNvs[activeNv] ? 1 : 0;
            ++activeNv;
        }
        activeNv = 0;
        paceDelayTmr = 1000;
    }
}
when (nv_update_succeeds(nvoTarget_1..nvoTarget_15)) {
    // Stop after all connected NVs are at their limits
    paceDelayTmr =  paceLoadValue;
}
when (nv_update_fails(nvoTarget_1..nvoTarget_15)) {
    // Tally the failure and move on
    s32_inc (&failTotal);
    nvoFailCount = failTotal;
    paceDelayTmr =  paceLoadValue;
}

when (msg_arrives){
    if (msg_in.code == DATA_REQUEST) {
        unsigned char msgData[64];
        unsigned int dataLength = msg_in.len;
        if (dataLength > 64)
            return;
        memcpy(msgData, msg_in.data, dataLength);
        resp_out.code = MSG_RESP_OK;
        memcpy(resp_out.data, msgData, dataLength);
        resp_send();
    }
}    

when(nv_update_occurs(nviCount))
{
   progressSt = !progressSt;
   io_out(LED2, progressSt);
   if (s32_eq(&nviCount, &s32_one)) {
        // Start of a test run. Receivers need to initialize performance counters
        // Senders see a reset to start a test.
        lastCountValue = s32_one;
        failTotal = s32_zero;
        nvoFailCount = failTotal;
   } else {
        s32_inc(&lastCountValue);
        if (s32_ne(&lastCountValue, &nviCount)) {
            s32_inc(&failTotal);
            nvoFailCount = failTotal;
        }
    lastCountValue = nviCount;
   }
}


when (reset)
{
    unsigned long startOffset;   
    if (commTester::cpUpdateRate) {
        // cpstartDelayTmr is based on SNVT_time_sec (0.1s resolution)
        // limit from 0 - 4.0s (4000ms) 0.2 is the practical lower limit with (16) senders
        // The solution is better tuned if we had a standard CP with msec resolution.
        if (commTester::cpStartDelay > 40UL) {
            startOffset = 4000;
        } else {
            startOffset = commTester::cpStartDelay * 100UL;
         }
            io_out (LED1, LED_ON);
            startDelayTmr = 10000 + startOffset;
        } else {
            startDelayTmr = 100UL;
        }
    // cpUpdateRate set to 0 makes this device a receiver
    paceLoadValue = commTester::cpUpdateRate;
    // converting SNVT_time_sec to ms.  Clipping to 5s
    paceLoadValue = paceLoadValue > 50 ? 5000 : paceLoadValue * 100UL;
}    

#endif //  _commTester_NC_


