//{{NodeBuilder Code Wizard Start <CodeWizard Timestamp>
// Run on Thu Mar 19 18:12:55 2026, version 4.40.15
//
//}}NodeBuilder Code Wizard End
//{{NodeBuilder Code Wizard Start <CodeWizard Template>
//// <Template Revision="3"/>
//}}NodeBuilder Code Wizard End

//////////////////////////////////////////////////////////////////////////////
// File: commTester.h
//
//
// Generated by NodeBuilder Code Wizard Version 4.40.15
// Copyright (c) 2026 EnOcean Edge Corporation.  All rights reserved.
//
// EnOcean E MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
// ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
// ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
// ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
// QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE,
// NONINFRINGEMENT, AND THEIR EQUIVALENTS.
//
//
// Written By:   
//
// Description:
//
// commTester.h contains the declarations required the implementation
// of commTester. The fblock commTester itself is declared below.
// The member network variables and configuration properties, if any, are also
// declared within this file. Finally, this file defines the prototype
// for a director function, commTesterDirector(), and a handler routine that
// processes input network variable updates, commTesterprocessNV().
// Both the director and the NV update handler function are implemented in
// commTester.nc, please see there for further details.
//
// This header file also is a good place for any type definitions, I/O object
// declarations or macro definitions that are for use by commTester, only.
//
//////////////////////////////////////////////////////////////////////////////

#ifndef _commTester_H_
#define _commTester_H_

#include "common.h"

//
// TODO: insert type or macro definitions, I/O object or any other declarations
// that are used by the commTester module alone here:
//

//{{NodeBuilder Code Wizard Start
// The NodeBuilder Code Wizard will add and remove code here.
// DO NOT EDIT the NodeBuilder Code Wizard generated code in these blocks
// between {{NodeBuilder Code Wizard Start and }}NodeBuilder Code Wizard End

//<Include Enum Type Headers>
//
//<Fblock Global Index>
#define FBLOCK_commTester_INDEX 	commTester::global_index
//
//<Forward FBDirector>
//msg_tag TAG1;
extern void commTesterDirector(unsigned uFblockIndex, int nCommand);
//
//<Fblock CP Family Declarations>
network input cp SCPTdelayTime cpStartDelay;
network input cp SCPTupdateRate cpUpdateRate;
network input cp SCPTmaxRnge cpTestLimit;
//
//<Fblock Input NV Declarations>
network input SNVT_count_32 nviCount;
//
//<Fblock Output NV Declarations>
network output SNVT_count_32 nvoTarget_1;
network output SNVT_count_32 nvoTarget_2;
network output SNVT_count_32 nvoTarget_3;
network output SNVT_count_32 nvoTarget_4;
network output SNVT_count_32 nvoTarget_5;
network output SNVT_count_32 nvoTarget_6;
network output SNVT_count_32 nvoTarget_7;
network output SNVT_count_32 nvoTarget_8;
network output SNVT_count_32 nvoTarget_9;
network output SNVT_count_32 nvoTarget_10;
network output SNVT_count_32 nvoTarget_11;
network output SNVT_count_32 nvoTarget_12;
network output SNVT_count_32 nvoTarget_13;
network output SNVT_count_32 nvoTarget_14;
network output SNVT_count_32 nvoTarget_15;
network output SNVT_count_32 nvoFailCount;
//
//<Fblock Declaration>
fblock UFPTcommTester {
   nviCount    implements nviCount;
   nvoTarget_1    implements nvoTarget_1;
   nvoTarget_2    implements nvoTarget_2;
   nvoTarget_3    implements nvoTarget_3;
   nvoTarget_4    implements nvoTarget_4;
   nvoTarget_5    implements nvoTarget_5;
   nvoTarget_6    implements nvoTarget_6;
   nvoTarget_7    implements nvoTarget_7;
   nvoTarget_8    implements nvoTarget_8;
   nvoTarget_9    implements nvoTarget_9;
   nvoTarget_10    implements nvoTarget_10;
   nvoTarget_11    implements nvoTarget_11;
   nvoTarget_12    implements nvoTarget_12;
   nvoTarget_13    implements nvoTarget_13;
   nvoTarget_14    implements nvoTarget_14;
   nvoTarget_15    implements nvoTarget_15;
   nvoFailCount    implements nvoFailCount;
   director    commTesterDirector;
} commTester
#ifdef USE_EXTERNAL_NAME
   external_name("commTester")
#endif
fb_properties {
   cpStartDelay,
   cpUpdateRate,
   cpTestLimit
};
//
//}}NodeBuilder Code Wizard End

// commTesterReportMask is used to report commTester's capabilities. It is defined
// in commTester.nc, please see there for details.
extern const SNVT_obj_status commTesterReportMask;

#endif // _commTester_H_


