
//{{NodeBuilder Code Wizard Start <CodeWizard Timestamp>
// Run on Thu Mar 19 18:12:55 2026, version 4.40.15
//
//}}NodeBuilder Code Wizard End
//{{NodeBuilder Code Wizard Start <CodeWizard Template>
//// <Template Revision="3"/>
//}}NodeBuilder Code Wizard End

//////////////////////////////////////////////////////////////////////////////
// File: commTester.nc
//
//
// Generated by NodeBuilder Code Wizard Version 4.40.15
// Copyright (c) 2001-2014 Echelon Corporation.  All rights reserved.
//
// ECHELON MAKES NO REPRESENTATION, WARRANTY, OR CONDITION OF
// ANY KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE OR IN
// ANY COMMUNICATION WITH YOU, INCLUDING, BUT NOT LIMITED TO,
// ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY
// QUALITY, FITNESS FOR ANY PARTICULAR PURPOSE,
// NONINFRINGEMENT, AND THEIR EQUIVALENTS.
//
//
// Written By:   
//
// Description:
//
// commTester.nc contains when-tasks, handler functions, director functions and
// any other code that is used with the commTester component.
//
// This file is a good place to add code for any additional processing that is
// specific to commTester, such as application timers, I/O events, interrupts,
// and so forth.
//
// Note this file also contains the commTesterReportMask variable,
// which is used to describe commTester's capabilities. See below for details.
//
//////////////////////////////////////////////////////////////////////////////

#ifndef _commTester_NC_
#define _commTester_NC_

#include "common.h"
#include <status.h>
#include <msg_addr.h>
#include <addrdefs.h>
#include<s32.h>
#include "commTester.h"


//
// TODO: Add code for any processing specific to commTester here.
// Such code includes declaration or processing of I/O objects, application
// timers or interrupt tasks, and so forth.
//
#define LED_ON 0
#define LED_OFF 1
#define NVO_COUNT 15

mtimer startDelayTmr;
mtimer paceDelayTmr;
mtimer repeating failFlashTmr;
// EVB 6050 LEDs left IO_2, right IO_3
IO_2 output bit LED1 =  LED_OFF;
IO_3 output bit LED2 = LED_OFF;

boolean boundNvs[NVO_COUNT];
boolean progressSt = LED_OFF;
unsigned activeNv = 0;
unsigned nvsInPlay = 0;
s32_type testCount;
s32_type failTotal;
msg_tag bind_info(nonbind) bcast_tag;
unsigned long paceLoadValue;

//
// Function to broadcast a clear status message to all nodes on the network
//
void broadcastClearStatus() {
    msg_out.tag = bcast_tag;
    msg_out.code = 0x53;  // ND_CLEAR_STATUS
    msg_out.service = UNACKD_RPT;
    msg_out.dest_addr.bcast.type = BROADCAST;
    msg_out.dest_addr.bcast.domain = 0;
    msg_out.dest_addr.bcast.subnet = 0; 
    msg_out.dest_addr.bcast.backlog = 0;
    msg_out.dest_addr.bcast.rpt_timer = 2; // 32ms
    msg_out.dest_addr.bcast.retry = 8; 
    msg_out.dest_addr.bcast.tx_timer = 0;
    msg_send();
}

void bumpActive() {
    switch (activeNv)
    {
    case 0:
        nvoTarget_1 = testCount;
        break;
    case 1:
        nvoTarget_2 = testCount;
        break;
    case 2:
        nvoTarget_3 = testCount;
        break;
    case 3:
        nvoTarget_4 = testCount;
        break;
    case 4:
        nvoTarget_5 = testCount;
        break;
    case 5:
        nvoTarget_6 = testCount;
        break; 
    case 6:
        nvoTarget_7 = testCount;
        break;  
    case 7:
        nvoTarget_8 = testCount;
        break;
    case 8:
        nvoTarget_9 = testCount;
        break;
    case 9:
        nvoTarget_10 = testCount;
        break;
    case 10:
        nvoTarget_11 = testCount;
        break;
    case 11:
        nvoTarget_12 = testCount;
        break;
    case 12:
        nvoTarget_13 =  testCount;
        break;  
    case 13:
        nvoTarget_14 = testCount;
        break;
    case 14:
        nvoTarget_15 = testCount;
        break;    
    case 16:
        // Test run termination 
        //io_out(LED2, LED_ON);
        if (s32_gt(&failTotal, &s32_zero))
            failFlashTmr = 200;
        break;
    default:
        break;
    }
}
when (timer_expires(paceDelayTmr)) {
    if (commTester::cpUpdateRate) {
        if (activeNv == 0)
            s32_inc(&testCount);
        bumpActive();
        activeNv = activeNv < (nvsInPlay - 1 )? activeNv + 1 : 0;

    } 
    // Stop after all connected NVs are at their limits
    if (s32_ge(&testCount, &commTester::cpTestLimit))
        paceDelayTmr = 0;
}
when (timer_expires(failFlashTmr)) {
    progressSt = !progressSt;
    io_out(LED2, progressSt);
}

when (timer_expires(startDelayTmr)) {

    // Only one device can drive the system.  Determine which NVs are in play
    if (commTester::cpUpdateRate) {
        broadcastClearStatus();
        io_out(LED1, LED_ON);
        boundNvs[0] = is_bound(nvoTarget_1);
        boundNvs[1] = is_bound(nvoTarget_2);
        boundNvs[2] = is_bound(nvoTarget_3);
        boundNvs[3] = is_bound(nvoTarget_4);
        boundNvs[4] = is_bound(nvoTarget_5);
        boundNvs[5] = is_bound(nvoTarget_6);
        boundNvs[6] = is_bound(nvoTarget_7);
        boundNvs[7] = is_bound(nvoTarget_8);
        boundNvs[8] = is_bound(nvoTarget_9);
        boundNvs[9] = is_bound(nvoTarget_10);
        boundNvs[10] = is_bound(nvoTarget_11);
        boundNvs[11] = is_bound(nvoTarget_12);
        boundNvs[12] = is_bound(nvoTarget_13);
        boundNvs[13] = is_bound(nvoTarget_14);
        boundNvs[14] = is_bound(nvoTarget_15);
        activeNv = 0;
        while (activeNv < NVO_COUNT) {
            nvsInPlay += boundNvs[activeNv] ? 1 : 0;
            ++activeNv;
        }
        activeNv = 0;
        paceDelayTmr = 1000;
    }
}
when (nv_update_succeeds(nvoTarget_1..nvoTarget_15)) {
        // Stop after all connected NVs are at their limits
    if (s32_ge(&testCount, &commTester::cpTestLimit) && activeNv == 0)
        paceDelayTmr = 0;
    else    
        paceDelayTmr =  paceLoadValue;
}
when (nv_update_fails(nvoTarget_1..nvoTarget_15)) {
    // Tally the failure and move on
    s32_inc (&failTotal);
    nvoFailCount = failTotal;
    if (s32_ge(&testCount, &commTester::cpTestLimit) && activeNv == 0)
        paceDelayTmr = 0;
    else    
        paceDelayTmr =  paceLoadValue;
}
    

//{{NodeBuilder Code Wizard Start
// The NodeBuilder Code Wizard will add and remove code here.
// DO NOT EDIT the NodeBuilder Code Wizard generated code in these blocks
// between {{NodeBuilder Code Wizard Start and }}NodeBuilder Code Wizard End

//<Input NV>
#ifndef _HAS_INP_NV_1
#define _HAS_INP_NV_1
#endif
//
//<Input NV Define>
//
// The following code will be ignored if this Neuron C file is used without
// an input NV implemented.  The Code Wizard automatically enables 
// the _HAS_INP_NV_1 macro if there is at least one input NV implemented.
//
#ifdef _HAS_INP_NV_1
//
//<Fblock NV When>
when(nv_update_occurs(nviCount))
//
//}}NodeBuilder Code Wizard End
{
    if (fblockNormalNotLockedOut(fblock_index_map[nv_in_index]))  {
       progressSt = !progressSt;
       io_out(LED2, progressSt);
    }
}
#endif  //_HAS_INP_NV


//
// commTesterDirector() manages commTester, and is called by the node object.
// When you add or remove capabilities to or from this functional block,
// make sure to update the commTesterReportMask constant, defined
// at the end of this file, to correctly describe this block's capabilities.
//
void commTesterDirector(unsigned uFblockIndex, int iCommand)
{
    TFblockData   *pStatus;
    unsigned long startOffset = 0;
    pStatus = getObjStatus(uFblockIndex);   // point to current status

    pStatus->invalid_request = FALSE;

    if (iCommand >= FBC_OBJECT_REQUEST_COUNT) {
        //
        // These commands originate from the node object. The director may take
        // action on these commands as appropriate, but it should never set the
        // invalid_request flag for one of these internal commands.
        // The invalid_request flag only relates to requests received through
        // the nviRequest network variable
        //

        if ((TFblock_command)iCommand == FBC_WHEN_RESET)  {

            //
            // TODO:
            // Add code to initialize this fblock (or fblock array) and all
            // related variables, I/O, etc, following a device reset.
            // Consider using the FBC_INITIALIZE_FB command, detailed below,
            // to perform this initialization.
            //
            if (commTester::cpUpdateRate) {
                // cpstartDelayTmr is based on SNVT_time_sec (0.1s resolution)
                // limit from 0 - 4.0s (4000ms)
                if (commTester::cpStartDelay > 40UL) {
                    startOffset = 4000;
                } else {
                    startOffset = commTester::cpStartDelay * 100UL;
                }
                io_out (LED1, LED_ON);
                startDelayTmr = 10000 + startOffset;
            } else {
                startDelayTmr = 100UL;
            }
            // cpUpdateRate set to 0 makes this device a receiver
            paceLoadValue = commTester::cpUpdateRate;
            // converting SNVT_time_sec to ms.  Clipping to 5s
            paceLoadValue = paceLoadValue > 50 ? 5000 : paceLoadValue * 100UL;

            
            setLockedOutBit(NODEOBJ_INDEX, TOTAL_FBLOCK_COUNT, uFblockIndex, FALSE);

        //
        // TODO:
        // Remove the '//' comment identifier from the following line of code,
        // if you wish to support fblock initialization through this director
        // function.
        //

//      } else if ((TFblock_command)iCommand == FBC_INITIALIZE_FB)  {

            //
            // TODO:
            // Add code to support the initialize command.
            // Note FBC_INITIALIZE_FB is a request code internal to this
            // applicaiton framework, and not received through the
            // standard NBCW_NODE_REQUEST variable.
            //
            // FBC_INITIALIZE_FB may be used as a generic function to
            // intialize the device and its fblocks. FBC_RESET command,
            // above, handles the special case of initialization in response
            // to a Neuron Chip reset, which in turn could use the
            // FBC_INITIALIZE_FB command. Other, application-specific, cases
            // may exist where a re-initialization is required.
            //
            // Typical initialization duties include the initialization of
            // attached I/O circuitry, driving any physical controls into a
            // well-defined state, initializing local variables, preparing
            // fblock-specific I/O models (for example, by calling
            // io_change_init()), and many other, application-specific tasks.
            //





        //
        // TODO:
        // Remove the '//' comment identifier from the following line of code,
        // if you wish to support the offline event for any fblock managed by
        // this director function.

//      } else if ((TFblock_command)iCommand == FBC_WHEN_OFFLINE)  {

            //
            // TODO:
            // Add code to respond to the offline command, if needed. Such
            // code might include action with regards to physically attached
            // hardware, or a visible indication showing that the fblock
            // is currently offline. Other possible actions include suspending
            // interrupt tasks or application timers.
            //
            // It is recommended to preserve the fblock's state prior to
            // changing the state to offline. When going back on line, the
            // original state can then be restored quickly, preserving other
            // state information of interrest, such as disable/enable or
            // override state information.
            //





        //
        // TODO:
        // Remove the '//' comment identifier from the following line of code,
        // if you wish to support the online event for any fblock managed by
        // this director function.

//      } else if ((TFblock_command)iCommand == FBC_WHEN_ONLINE)  {

            //
            // TODO:
            // Add code to respond to the online command, if needed.
            // Such code need to revert changes that were made when the fblock
            // was taken offline, and would typically consider the historic
            // state information that was saved when entering the offline state.
            //





        //
        // TODO:
        // Remove the '//' comment identifier from the following line of code,
        // if you wish to support a device-level heartbeat timer.
        //

//      } else if ((TFblock_command)iCommand == FBC_SEND_HEARTBEAT_TIMER)  {

            //
            // TODO:
            // Add code to support the command.
            // Note supporting FBC_SEND_HEARTBEAT_TIMER is not required; this
            // command is provided for your convenience and as an example for
            // a possible heartbeat implementation.
            // The heartbeat is controlled by SCPTmaxSndT and SCPTmaxSendTime
            // configuration properties; see http://types.lonmark.org for more.
            //





        }  // end of interal director command dispatch

    //
    // Following are implementations and implementation fragments to handle
    // the standard requests received through the NodeObject's nviRequest
    // variable.

    } else if ((TFblock_command)iCommand == FBC_NORMAL) {

        //
        // An FBC_NORMAL request must always be honored. It must remove the
        // disabled state (if the fblock was disabled), and it must enable the
        // fblock (if it was disabled).
        // The following code implements these state transitions through
        // recursively calls the director function. The disabled state has
        // higher priority than the override state (an object that is both
        // in override and disabled is consiered disabled); the order of the
        // state transitions implemented below reflects this rule.
        // Changing the order of the following recursive calls will cause the
        // fblock to transit through the override state after the object has
        // been re-enabled, possibly causing undesired effects.
        // DO NOT CHANGE THE ORDER OF THE FOLLOWING DIRECTOR CALLS:

        if (pStatus->in_override) {
            commTesterDirector(uFblockIndex, FBC_RMV_OVERRIDE);
        }
        if ( pStatus->disabled ) {
            commTesterDirector(uFblockIndex, FBC_ENABLE);
        }

        //
        // TODO:
        // Add additional code , if needed.
        // Additional code to support this command is not normally required.
        //





    } else if ((TFblock_command)iCommand == FBC_CLEAR_STATUS) {

        // Additional code to support this command is not normally required.
        // The clearFblockStatus() utility function clears the status
        // information of a given fblock while preserving its alarm and state
        // details.

        clearFblockStatus(uFblockIndex);

    } else if ((TFblock_command)iCommand == FBC_UPDATE_STATUS)  {

        // Additional code to support this command is not normally required.
        // The default implementation for the Node Object correctly updates
        // the device and object status information.

    } else if ((TFblock_command)iCommand == FBC_DISABLED)  {

        //
        // TODO:
        // Add code to support the disable command. When an fblock is disabled,
        // it should play its default value. For a sensor-type fblock, the
        // relevant output network variables should report this default value.
        // For an actuator-type fblock, the physical hardware attached to this
        // device should be driven with the default value. This default value
        // might be hard-coded, or could be configuable through a SCPTdefOutput
        // configuration property.
        //

        setFblockDisable(NODEOBJ_INDEX, TOTAL_FBLOCK_COUNT, uFblockIndex, TRUE);





    } else if ((TFblock_command)iCommand == FBC_ENABLE)  {

        //
        // TODO:
        // Add code to support the enable command. When a fblock is enabled, it
        // must show the correct behavior for this state: override mode, etc.
        // When enabling a functional block, network variables or I/O circuitry
        // may need updating, application timers or interrupts may need managing,
        // etc.
        //

        setFblockDisable(NODEOBJ_INDEX, TOTAL_FBLOCK_COUNT, uFblockIndex, FALSE);

        //
        // TODO:
        // Add other, application-specific, code to manage enabling this
        // fblock's functionality. This could require updating network
        // variables or I/O objects, managing application timers or interrupts,
        // and so forth.
        //

        if ( pStatus->in_override ) {

            //
            // TODO:
            // Restore I/O circuitry and/or output network variable(s) reflect
            // the override values and -behavior.
            //





        } else {

            //
            // TODO:
            // Restore I/O circuitry and/or output network variable(s) reflect
            // the normal values and -behavior.
            //





        }
    } else if ((TFblock_command)iCommand == FBC_OVERRIDE)  {

        //
        // TODO:
        // Add code to enter the override state. When an fblock is overridden,
        // it must play the override value according to the specified override
        // behavior. Note that an fblock might be both disabled and overridden
        // at the same time. In this case, the disabled state takes priority.
        //

        setFblockOverride(NODEOBJ_INDEX, TOTAL_FBLOCK_COUNT, uFblockIndex, TRUE);

        if ( !pStatus->disabled ) {

            //
            // TODO:
            // Adjust output network variable(s) and/or I/O circuitry according
            // to the specified override behavior and override values.
            //





        }

    } else if ((TFblock_command)iCommand == FBC_RMV_OVERRIDE)  {

        //
        // TODO:
        // Add code to remove the override command. When a fblock leaves the
        // override state, it must play the normal control or process value
        // unless the fblock is disabled. In case the flbock is disabled,
        // the fblock must continue to play the values valid for the disabled
        // state, as the disabled state has the higher priority.

        setFblockOverride(NODEOBJ_INDEX, TOTAL_FBLOCK_COUNT, uFblockIndex, FALSE);

        if ( !pStatus->disabled ) {

            //
            // TODO:
            // Restore I/O circuitry and/or output network variable(s) to
            // reflect the current process or control values.
            //





        }

    } else if ((TFblock_command)iCommand == RQ_REPORT_MASK)  {
        NBCW_NODE_STATUS = commTesterReportMask;

    //
    // TODO:
    // Remove the '//' comment identifier from the following line of code,
    // if you wish to support self-testing
    //

//      } else if ((TFblock_command)iCommand == FBC_SELF_TEST) {

        //
        // TODO:

        // TODO: Add code to support self-test commands. Note the default
        // implementation here does *not* support self-test, and it sets
        // "invalid_request" to TRUE, indicating that self-test is not
        // supported.
        // This is because a generic device implementation cannot provide
        // meaningful self-test support.
        // It is recommended that you add code to support testing of the
        // entire LonWorks device, including I/O circuitry, as appropriate.
        //
        // Depending on the duration of your device's self-test procedures,
        // one of the following two alternative approaches is recommended:
        //
        // (a) self-test takes very short time to complete.
        //     The self-test routine may be called from this fblock director
        //     directly, and the director function itself may return to its
        //     caller once the self-test routine is completed.
        //     Since the device application cannot respond while the self-test
        //     is running, this simple method is only suitable for self-test
        //     routines that complete in less than one second.
        //
        // (b) self-test may take longer to complete.
        //     In this case, the director function should change the object's
        //     state into self_test_in_progress, start the self-test routine
        //     and return to the caller as soon as possible. The device's or
        //     fblock's state engine continues to drive the self-test process
        //     until it has been completed with success or failure, and clear
        //     the self_test_in_progress state.
        //
        //     It is recommended that any self-test routine should complete
        //     with success or failure within 20 seconds or less.
        //





    } else {
        //
        // Unsupported request:
        //
        pStatus->invalid_request = TRUE;
    }
}


// commTesterReportMask is a constant bitvector, reporting
// the capabilities of the commTester component.
// You may change the default capabilities, however, whenever changes are made
// to the ReportMask constant, the commTesterDirector() function
// must be updated to implement the matching behavior.
// Also note changing the report mask of fblocks other than the node object
// typically requires also changing the node object's own report mask.
// It is recommended NOT to remove support for 'disabled', 'locked out',
// and 'report mask'.
const SNVT_obj_status commTesterReportMask = {
    0,              // object_id

    0,              // invalid_id
    0,              // invalid_request
    1,              // disabled
    0,              // out_of_limits
    0,              // open_circuit
    0,              // out_of_service
    0,              // mechanical_fault
    0,              // feedback_failure

    0,              // over_range
    0,              // under_range
    0,              // electrical_fault
    0,              // unable_to_measure
    1,              // comm_failure
    0,              // fail_self_test
    0,              // self_test_in_progress
    1,              // locked_out

    0,              // manual_control
    0,              // in_alarm
    1,              // in_override
    1,              // report_mask
    0,              // programming_mode
    0,              // programming_failed
    0,              // alarm_notify_disabled
    0               // reset_complete
};

#endif //  _commTester_NC_


